export const CELL_SIZE = 35;
export const COLS = 40;
export const ROWS = 25;
export const VISIBILITY_RADIUS = 100;
export const PLAYER_SPEED = 1;
export const PLAYER_RADIUS = 15;
export const TIME_LIMIT = 60;
export const REVEAL_WALLS= false;
export const TOTAL_REWARDS = 5;
